# Generated by Django 3.2.7 on 2021-09-29 22:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^(\\+\\d{1,3})?,?\\s?\\d{9,14}')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of otp sent')),
                ('validated', models.BooleanField(default=False, help_text='If it true, that means user have validate otp correctly in second API')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='Nom du type de transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 14 digits are allowed", regex='^(\\+\\d{1,3})?,?\\s?\\d{10,14}')])),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('usd_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cdf_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_staff', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('shop_assistant', models.BooleanField(default=False)),
                ('client', models.BooleanField(default=False)),
                ('agent', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de transaction')),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montat de la transaction')),
                ('trans_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Coût de la transaction')),
                ('recever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiare')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_senders', to=settings.AUTH_USER_MODEL, verbose_name='Acteur de la transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kmodels.type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montat de la facture')),
                ('bill_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de livraison')),
                ('is_payed', models.BooleanField(default=False, verbose_name='La facture est payer')),
                ('recipient', models.ManyToManyField(related_name='recipients', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaire')),
                ('shop_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Délivreur de la facture')),
                ('transation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kmodels.transaction', verbose_name='Paiement lier à la facture')),
            ],
        ),
        migrations.CreateModel(
            name='AgentSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de transaction')),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montat de la transaction')),
                ('trans_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Coût de la transaction')),
                ('benefit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interêt de recharge')),
                ('recever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiare')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL, verbose_name='Acteur de la transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kmodels.type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
