# Generated by Django 3.2.7 on 2021-09-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kmodels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsupply',
            name='id',
        ),
        migrations.RemoveField(
            model_name='agentsupply',
            name='recever',
        ),
        migrations.RemoveField(
            model_name='agentsupply',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='agentsupply',
            name='trans_amount',
        ),
        migrations.RemoveField(
            model_name='agentsupply',
            name='trans_cost',
        ),
        migrations.RemoveField(
            model_name='agentsupply',
            name='trans_date',
        ),
        migrations.RemoveField(
            model_name='agentsupply',
            name='type',
        ),
        migrations.AddField(
            model_name='agentsupply',
            name='transaction_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Kmodels.transaction'),
            preserve_default=False,
        ),
    ]
