# Generated by Django 3.2.7 on 2021-10-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kmodels', '0003_auto_20210930_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='bill_date',
            new_name='bill_sumbit_date',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_motif',
            field=models.CharField(default=1, max_length=250, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_payed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.RemoveField(
            model_name='bill',
            name='recipient',
        ),
        migrations.AddField(
            model_name='bill',
            name='recipient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='Kmodels.client', verbose_name='Bénéficiaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='cdf_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='usd_balance',
            field=models.FloatField(default=0),
        ),
    ]
