# Generated by Django 3.2.7 on 2021-10-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kmodels', '0004_auto_20211001_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='bill_sumbit_date',
            new_name='bill_submit_date',
        ),
    ]
