# Generated by Django 3.2.8 on 2021-10-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kmodels', '0005_rename_bill_sumbit_date_bill_bill_submit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsupply',
            name='benefit',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='count',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trans_cost',
        ),
        migrations.AddField(
            model_name='agentsupply',
            name='cdf_benefit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Interêt de recharge en cdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentsupply',
            name='usd_benefit',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Interêt de recharge en usd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='cdf_trans_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Coût de la transaction en cdf'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='usd_trans_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Coût de la transaction en usd'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
