# Generated by Django 3.2.8 on 2021-10-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kmodels', '0006_auto_20211010_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsupply',
            name='cdf_benefit',
        ),
        migrations.RemoveField(
            model_name='agentsupply',
            name='usd_benefit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cdf_trans_cost',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='usd_trans_cost',
        ),
        migrations.AddField(
            model_name='agentsupply',
            name='benefit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Interêt de recharge'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Coût de la transaction'),
        ),
    ]
