# Generated by Django 3.2.8 on 2021-10-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kmodels', '0007_auto_20211010_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.CharField(default=2, max_length=50, verbose_name='Devise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='service',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
